# 9 Ensamblador

### 9.9 Objetivo

Ensamblar modelos YA construidos
Los modelos a ensamblar deben ser de la misma Modalidad
 * Este script está armado para Analista Sr
 * Este script corre unicamente en Google Cloud

## 9.9.1  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Aug 24 20:58:09 2025"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  656928 35.1 1439368    76.9 1431354  76.5
Vcells 1225095  9.4 8388608    64.0 1924965  14.7

In [3]:
require("data.table")

Loading required package: data.table

#### Parametros

Se debe poner en PARAM$modelos  la lista de modelos que se va a ensamblar, y deben ser por lo menos DOS

In [20]:
PARAM <- list()
PARAM$modelos <- c( "WF950106", "WF950107", "WF950108","WF950109","WF950103","WF950104","WF950111", "WF950110" )

PARAM$experimento <- 999004

#### Carpeta del Experimento

In [21]:
# carpeta de trabajo

setwd("~/buckets/b1/exp")
experimento_folder <- paste0("EN", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("~/buckets/b1/exp/", experimento_folder ))

### 9.9.2   Ensamblado

In [22]:
# lectura del primer  predicion.txt
tb_prediccion  <-  fread( paste0( "~/buckets/b1/exp/", PARAM$modelos[1], "/prediccion.txt" ) )
tb_prediccion <- tb_prediccion[,c("numero_de_cliente", "prob"), with=FALSE]
setorder(tb_prediccion, numero_de_cliente)

In [23]:
buenos <- 1 
for( imodelo in seq(2, length(PARAM$modelos)) )
{
  tbl <- fread( paste0( "~/buckets/b1/exp/", PARAM$modelos[imodelo], "/prediccion.txt" ) )
  if( nrow(tbl) == nrow( tb_prediccion ) )
    {
      setorder(tbl, numero_de_cliente)
      tb_prediccion[, prob := prob + tbl$prob ]
      buenos <- buenos +1 
    }
}

# fui sumando, ahora divido por la cantidad para tener el promedio
tb_prediccion[, prob := prob / buenos ]

# grabo a disto, esto SI PUEDE ser reutilizado
fwrite( tb_prediccion,
  file = "prediccion.txt",
  sep= "\t"
)

In [24]:
tb_prediccion

       numero_de_cliente prob
1      29183733          0.0007941682
2      29184468          0.0006853026
3      29185245          0.0153689732
4      29186441          0.0014503692
5      29186475          0.0014268524
6      29187730          0.0006812028
7      29187764          0.0009314395
8      29187961          0.0017300993
9      29189899          0.0014660757
10     29189993          0.0022029263
11     29190113          0.0011008940
12     29192179          0.0028282274
13     29193101          0.0020831717
14     29193281          0.0014389073
15     29193324          0.0059130138
16     29195356          0.0096136115
17     29195433          0.0006457795
18     29196099          0.0031641043
19     29196902          0.0021312462
20     29198055          0.0006716629
21     29198891          0.0031316003
22     29199242          0.0052184684
23     29200335          0.0006660134
24     29200343          0.0024711564
25     29200514          0.0062183241
26     29200651          0.0092545869
27     29200727          0.0018189575
28     29200770          0.0006369389
29     29200984          0.0021387268
30     29201086          0.0007785915
⋮      ⋮                 ⋮
165064 187967614         0.012055522
165065 187969270         0.016800063
165066 187989740         0.020740293
165067 187999433         0.006496513
165068 188009390         0.016947338
165069 188009578         0.017531591
165070 188015094         0.003959491
165071 188017716         0.008201177
165072 188019279         0.024681242
165073 188031482         0.005324720
165074 188042080         0.016882060
165075 188054394         0.006381418
165076 188055368         0.025299818
165077 188057878         0.017075070
165078 188061679         0.004365827
165079 188062558         0.017547273
165080 188064497         0.013285724
165081 188071815         0.013771388
165082 188073113         0.019536837
165083 188074787         0.016931007
165084 188084847         0.002025429
165085 188096188         0.025753829
165086 188097537         0.019286839
165087 188100654         0.015963885
165088 188101739         0.016046975
165089 188115120         0.014591519
165090 188116871         0.002817656
165091 188122277         0.006058373
165092 188128903         0.018729065
165093 188136205         0.016639754

### 9.9.3 Kaggle Competition Submit

Genero las salidas y hago los submits a Kaggles

In [25]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

PARAM$kaggle$competencia <- "data-mining-analista-sr-2025-a"
PARAM$kaggle$cortes <- seq(500, 12000, by = 500)

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle")

for (envios in PARAM$kaggle$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marclo los primeros

  archivo_kaggle <- paste0(
    "./kaggle/EN",
    PARAM$experimento, "_",
    envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  # subida a Kaggle, armo la linea de comando
  comando <- "kaggle competitions submit"
  competencia <- paste("-c", PARAM$kaggle$competencia)
  arch <- paste( "-f", archivo_kaggle)

  mensaje <- paste0("-m 'envios=", envios, "  Ensemble", "'" )

  linea <- paste( comando, competencia, arch, mensaje)

  salida <- system(linea, intern=TRUE) # el submit a Kaggle
  cat(salida, "\n")
}

Successfully submitted to Data Mining, Analista Sr 2025A
Successfully submitted to Data Mining, Analista Sr 2025A
Successfully submitted to Data Mining, Analista Sr 2025A

In [10]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Aug 24 21:02:26 2025"