# 9 Ensamblador

### 9.9 Objetivo

Ensamblar modelos YA construidos
Los modelos a ensamblar deben ser de la misma Modalidad
 * Este script está armado para Analista Sr
 * Este script corre unicamente en Google Cloud

## 9.9.1  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [25]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Aug 24 23:28:25 2025"

In [26]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb)  max used (Mb)
Ncells  724174 38.7  1435128    76.7  1435128  76.7
Vcells 1374162 10.5 15395680   117.5 18244271 139.2

In [27]:
require("data.table")

Loading required package: data.table

#### Parametros

Se debe poner en PARAM$modelos  la lista de modelos que se va a ensamblar, y deben ser por lo menos DOS

In [29]:
PARAM <- list()
PARAM$modelos <- c( "WF950106", "WF950107", "WF950108","WF950109","WF950111","WF950110")

PARAM$experimento <- 999008

#### Carpeta del Experimento

In [30]:
# carpeta de trabajo

setwd("~/buckets/b1/exp")
experimento_folder <- paste0("EN", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("~/buckets/b1/exp/", experimento_folder ))

### 9.9.2   Ensamblado

In [31]:
# lectura del primer  predicion.txt
tb_prediccion  <-  fread( paste0( "~/buckets/b1/exp/", PARAM$modelos[1], "/prediccion.txt" ) )
tb_prediccion <- tb_prediccion[,c("numero_de_cliente", "prob"), with=FALSE]
setorder(tb_prediccion, numero_de_cliente)

In [32]:
buenos <- 1 
for( imodelo in seq(2, length(PARAM$modelos)) )
{
  tbl <- fread( paste0( "~/buckets/b1/exp/", PARAM$modelos[imodelo], "/prediccion.txt" ) )
  if( nrow(tbl) == nrow( tb_prediccion ) )
    {
      setorder(tbl, numero_de_cliente)
      tb_prediccion[, prob := prob + tbl$prob ]
      buenos <- buenos +1 
    }
}

# fui sumando, ahora divido por la cantidad para tener el promedio
tb_prediccion[, prob := prob / buenos ]

# grabo a disto, esto SI PUEDE ser reutilizado
fwrite( tb_prediccion,
  file = "prediccion.txt",
  sep= "\t"
)

In [33]:
tb_prediccion

       numero_de_cliente prob
1      29183733          0.0006670274
2      29184468          0.0005206846
3      29185245          0.0155829768
4      29186441          0.0012281139
5      29186475          0.0012047245
6      29187730          0.0005224607
7      29187764          0.0007587509
8      29187961          0.0015736938
9      29189899          0.0012704589
10     29189993          0.0020175002
11     29190113          0.0008706350
12     29192179          0.0026370770
13     29193101          0.0019029657
14     29193281          0.0012263442
15     29193324          0.0056731664
16     29195356          0.0101899443
17     29195433          0.0004774120
18     29196099          0.0029995621
19     29196902          0.0017139666
20     29198055          0.0005129322
21     29198891          0.0028617736
22     29199242          0.0049758338
23     29200335          0.0005039111
24     29200343          0.0022012785
25     29200514          0.0059028397
26     29200651          0.0094587427
27     29200727          0.0016588065
28     29200770          0.0004667682
29     29200984          0.0019239649
30     29201086          0.0006108653
⋮      ⋮                 ⋮
165064 187967614         0.012460335
165065 187969270         0.016982343
165066 187989740         0.020999569
165067 187999433         0.006156703
165068 188009390         0.017174090
165069 188009578         0.017853255
165070 188015094         0.003924510
165071 188017716         0.007870044
165072 188019279         0.027030154
165073 188031482         0.005124522
165074 188042080         0.017100057
165075 188054394         0.006639308
165076 188055368         0.025428345
165077 188057878         0.016833922
165078 188061679         0.004525381
165079 188062558         0.017901205
165080 188064497         0.013714942
165081 188071815         0.013492234
165082 188073113         0.019912401
165083 188074787         0.017132661
165084 188084847         0.001958723
165085 188096188         0.026083641
165086 188097537         0.019621746
165087 188100654         0.016037056
165088 188101739         0.016162026
165089 188115120         0.013890082
165090 188116871         0.002740489
165091 188122277         0.006258663
165092 188128903         0.018936398
165093 188136205         0.016786534

### 9.9.3 Kaggle Competition Submit

Genero las salidas y hago los submits a Kaggles

In [9]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

PARAM$kaggle$competencia <- "data-mining-analista-sr-2025-a"
PARAM$kaggle$cortes <- seq(9000, 12000, by = 500)

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle")

for (envios in PARAM$kaggle$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marclo los primeros

  archivo_kaggle <- paste0(
    "./kaggle/EN",
    PARAM$experimento, "_",
    envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  # subida a Kaggle, armo la linea de comando
  comando <- "kaggle competitions submit"
  competencia <- paste("-c", PARAM$kaggle$competencia)
  arch <- paste( "-f", archivo_kaggle)

  mensaje <- paste0("-m 'envios=", envios, "  Ensemble", "'" )

  linea <- paste( comando, competencia, arch, mensaje)

  salida <- system(linea, intern=TRUE) # el submit a Kaggle
  cat(salida, "\n")
}

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c data-mining-analista-sr-2025-a -f ./kaggle/EN999008_9000.csv -m 'envios=9000  Ensemble'' had status 1”

In [10]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Aug 24 23:24:57 2025"